import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// my imports
import ReactChildrenNode from '@/interfaces/node'
//

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DataX',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: ReactChildrenNode) {
  return (
    <html lang="en">
      <body className={`bg-background-black ${inter.className}`}>
        {children}
      </body>
    </html>
  )
}
